In [1]:
import cv2
cap = cv2.VideoCapture("c:\\opencv_test\\01_People.avi")
while(True):    
    bw, img = cap.read()
    #print(bw)
    orb = cv2.ORB_create()
    kp = orb.detect(img,None)
    kp, des = orb.compute(img, kp)
    img2 = cv2.drawKeypoints(img,kp,None,color=(0,0,255), flags=0)
    cv2.imshow("ORB-SLAM", img2)
    if cv2.waitKey(1)==13:
        break
cap.release()
cv2.destroyAllWindows()

KeyboardInterrupt: 

In [4]:
#1)ndarray를 이용한 레이아웃을 실행
import numpy as np
import cv2
image = np.zeros((200,400),np.uint8)
print(image)
image[:] = 200  #흰색바탕
print(image)

title01, title02 = "test01", "test02"  #윈도우타이틀 값
cv2.namedWindow(title01,cv2.WINDOW_AUTOSIZE)
cv2.namedWindow(title02)

cv2.moveWindow(title01,150,150) #윈도우 이동
cv2.moveWindow(title02,400,50)

#행 열을 이미지 보기
cv2.imshow(title01, image)
cv2.imshow(title02, image)
cv2.waitKey(0)  #키 이벤트
cv2.destroyAllWindows() # 객체소멸

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[200 200 200 ... 200 200 200]
 [200 200 200 ... 200 200 200]
 [200 200 200 ... 200 200 200]
 ...
 [200 200 200 ... 200 200 200]
 [200 200 200 ... 200 200 200]
 [200 200 200 ... 200 200 200]]


In [5]:
#1)ndarray를 이용한 레이아웃을 실행
# 윈도우 사이즈 변경 resizeWindow(타이틀, w, h)
import numpy as np
import cv2
image = np.zeros((200,300),np.uint8)
image.fill(255)

title01, title02 = "test01", "test02"  #윈도우타이틀 값
cv2.namedWindow(title01,cv2.WINDOW_AUTOSIZE)
cv2.namedWindow(title02,cv2.WINDOW_NORMAL)

#행 열을 이미지 보기
cv2.imshow(title01, image)
cv2.imshow(title02, image)

#윈도우 사이즈 변경
cv2.resizeWindow(title01,400,300)
cv2.resizeWindow(title02,400,300)

cv2.waitKey(0)  #키 이벤트
cv2.destroyAllWindows() # 객체소멸

In [9]:
#3) 마우스 이벤트 속성값을 활용해보자. setMouseCallback(windowName, onMouse [, param]) -> None
#full(shape, fill_value, dtype+None, order ='C')

#1)ndarray를 이용한 레이아웃을 실행
# 윈도우 사이즈 변경 resizeWindow(타이틀, w, h)
import numpy as np
import cv2

def onMouse(event,x,y,flags,param):
    if event ==cv2.EVENT_LBUTTONDOWN:
        print("왼쪽 마우스 클릭",event,x,y,flags,param)
    
    elif event ==cv2.EVENT_RBUTTONDOWN:
        print("오른쪽 마우스 클릭",event,x,y,flags,param)
        
    elif event ==cv2.EVENT_LBUTTONUP:
        print("왼쪽 마우스 UP",event,x,y,flags,param)
        
    elif event ==7:
        print("왼쪽 마우스 double_Click",event,x,y,flags,param)
    
image = np.full((200,300),255,np.uint8) #배열로 이미지 생성

title01, title02 = "test01", "test02"  #윈도우타이틀 값
cv2.imshow(title01, image)
cv2.imshow(title02, image)

# 마우스 이벤트 연동
cv2.setMouseCallback("test01",onMouse) #마우스 콜백 함수
cv2.waitKey(0)  #키 이벤트
cv2.destroyAllWindows() # 객체소멸


왼쪽 마우스 클릭 1 162 88 1 None
왼쪽 마우스 UP 4 162 88 0 None
왼쪽 마우스 클릭 1 162 88 1 None
왼쪽 마우스 UP 4 162 88 0 None
오른쪽 마우스 클릭 2 162 88 2 None
왼쪽 마우스 클릭 1 162 88 1 None
왼쪽 마우스 UP 4 162 88 0 None
왼쪽 마우스 double_Click 7 162 88 1 None
왼쪽 마우스 UP 4 162 88 0 None
왼쪽 마우스 클릭 1 188 112 1 None
왼쪽 마우스 UP 4 188 112 0 None


In [12]:
#4) createTrackbar 생성
#createTrackbar(const String & trackbarname, const String & winname, int * value, int count, TrackbarCallback 	onChange = 0, void * userdata = 0 )
# (트랙바 이름, 윈도우 이름, 트랙바값, 개수, onChange, 파람)

import numpy as np
import cv2

def onChange(value): #트랙바의 콜백함수
    global image # 전역변수
    
    res = value - int(image[0][0])  #트랙바 값 - 이미지 화소
    image = image + res
    print(image[0][0],res,image)
    cv2.imshow(title01,image)

image = np.zeros((200,600),np.uint8) #배열로 이미지 생성

title01 = "test01"  #윈도우타이틀 값
cv2.imshow(title01, image)

# 트랙바 연동
cv2.createTrackbar("Mytrack","test01",image[0][0],255,onChange) #마우스 콜백 함수
cv2.waitKey(0)  #키 이벤트
cv2.destroyAllWindows() # 객체소멸

1 1 [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
2 1 [[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
3 1 [[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
5 2 [[5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 ...
 [5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]
 [5 5 5 ... 5 5 5]]
6 1 [[6 6 6 ... 6 6 6]
 [6 6 6 ... 6 6 6]
 [6 6 6 ... 6 6 6]
 ...
 [6 6 6 ... 6 6 6]
 [6 6 6 ... 6 6 6]
 [6 6 6 ... 6 6 6]]
7 1 [[7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]
 ...
 [7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]]
8 1 [[8 8 8 ... 8 8 8]
 [8 8 8 ... 8 8 8]
 [8 8 8 ... 8 8 8]
 ...
 [8 8 8 ... 8 8 8]
 [8 8 8 ... 8 8 8]
 [8 8 8 ... 8 8 8]]
9 1 [[9 9 9 ... 9 9 9]
 [9 9 9 ... 9 9 9]
 [9 9 9 ... 9 9 9]
 ...
 [9 9 9 ... 9 9 9]
 [9 9 9 ... 9 9 9]
 [9 9 9 ... 9 9 9]]
10 1 [[1

108 1 [[108 108 108 ... 108 108 108]
 [108 108 108 ... 108 108 108]
 [108 108 108 ... 108 108 108]
 ...
 [108 108 108 ... 108 108 108]
 [108 108 108 ... 108 108 108]
 [108 108 108 ... 108 108 108]]
109 1 [[109 109 109 ... 109 109 109]
 [109 109 109 ... 109 109 109]
 [109 109 109 ... 109 109 109]
 ...
 [109 109 109 ... 109 109 109]
 [109 109 109 ... 109 109 109]
 [109 109 109 ... 109 109 109]]
160 51 [[160 160 160 ... 160 160 160]
 [160 160 160 ... 160 160 160]
 [160 160 160 ... 160 160 160]
 ...
 [160 160 160 ... 160 160 160]
 [160 160 160 ... 160 160 160]
 [160 160 160 ... 160 160 160]]
211 51 [[211 211 211 ... 211 211 211]
 [211 211 211 ... 211 211 211]
 [211 211 211 ... 211 211 211]
 ...
 [211 211 211 ... 211 211 211]
 [211 211 211 ... 211 211 211]
 [211 211 211 ... 211 211 211]]
215 4 [[215 215 215 ... 215 215 215]
 [215 215 215 ... 215 215 215]
 [215 215 215 ... 215 215 215]
 ...
 [215 215 215 ... 215 215 215]
 [215 215 215 ... 215 215 215]
 [215 215 215 ... 215 215 215]]
216 1 [[

138 -2 [[138 138 138 ... 138 138 138]
 [138 138 138 ... 138 138 138]
 [138 138 138 ... 138 138 138]
 ...
 [138 138 138 ... 138 138 138]
 [138 138 138 ... 138 138 138]
 [138 138 138 ... 138 138 138]]
135 -3 [[135 135 135 ... 135 135 135]
 [135 135 135 ... 135 135 135]
 [135 135 135 ... 135 135 135]
 ...
 [135 135 135 ... 135 135 135]
 [135 135 135 ... 135 135 135]
 [135 135 135 ... 135 135 135]]
132 -3 [[132 132 132 ... 132 132 132]
 [132 132 132 ... 132 132 132]
 [132 132 132 ... 132 132 132]
 ...
 [132 132 132 ... 132 132 132]
 [132 132 132 ... 132 132 132]
 [132 132 132 ... 132 132 132]]
130 -2 [[130 130 130 ... 130 130 130]
 [130 130 130 ... 130 130 130]
 [130 130 130 ... 130 130 130]
 ...
 [130 130 130 ... 130 130 130]
 [130 130 130 ... 130 130 130]
 [130 130 130 ... 130 130 130]]
128 -2 [[128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 ...
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]]
124 -

1 1 [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]
3 2 [[3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 ...
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]
 [3 3 3 ... 3 3 3]]
7 4 [[7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]
 ...
 [7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]
 [7 7 7 ... 7 7 7]]
9 2 [[9 9 9 ... 9 9 9]
 [9 9 9 ... 9 9 9]
 [9 9 9 ... 9 9 9]
 ...
 [9 9 9 ... 9 9 9]
 [9 9 9 ... 9 9 9]
 [9 9 9 ... 9 9 9]]
12 3 [[12 12 12 ... 12 12 12]
 [12 12 12 ... 12 12 12]
 [12 12 12 ... 12 12 12]
 ...
 [12 12 12 ... 12 12 12]
 [12 12 12 ... 12 12 12]
 [12 12 12 ... 12 12 12]]
13 1 [[13 13 13 ... 13 13 13]
 [13 13 13 ... 13 13 13]
 [13 13 13 ... 13 13 13]
 ...
 [13 13 13 ... 13 13 13]
 [13 13 13 ... 13 13 13]
 [13 13 13 ... 13 13 13]]
16 3 [[16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]
 ...
 [16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]]
20 4 [[20 20 20 ... 2

246 1 [[246 246 246 ... 246 246 246]
 [246 246 246 ... 246 246 246]
 [246 246 246 ... 246 246 246]
 ...
 [246 246 246 ... 246 246 246]
 [246 246 246 ... 246 246 246]
 [246 246 246 ... 246 246 246]]
247 1 [[247 247 247 ... 247 247 247]
 [247 247 247 ... 247 247 247]
 [247 247 247 ... 247 247 247]
 ...
 [247 247 247 ... 247 247 247]
 [247 247 247 ... 247 247 247]
 [247 247 247 ... 247 247 247]]
248 1 [[248 248 248 ... 248 248 248]
 [248 248 248 ... 248 248 248]
 [248 248 248 ... 248 248 248]
 ...
 [248 248 248 ... 248 248 248]
 [248 248 248 ... 248 248 248]
 [248 248 248 ... 248 248 248]]
249 1 [[249 249 249 ... 249 249 249]
 [249 249 249 ... 249 249 249]
 [249 249 249 ... 249 249 249]
 ...
 [249 249 249 ... 249 249 249]
 [249 249 249 ... 249 249 249]
 [249 249 249 ... 249 249 249]]
252 3 [[252 252 252 ... 252 252 252]
 [252 252 252 ... 252 252 252]
 [252 252 252 ... 252 252 252]
 ...
 [252 252 252 ... 252 252 252]
 [252 252 252 ... 252 252 252]
 [252 252 252 ... 252 252 252]]
255 3 [[25

In [17]:
#4) createTrackbar 생성
#createTrackbar(const String & trackbarname, const String & winname, int * value, int count, TrackbarCallback 	onChange = 0, void * userdata = 0 )
# (트랙바 이름, 윈도우 이름, 트랙바값, 개수, onChange, 파람)

import numpy as np
import cv2

def onChange(value): #트랙바의 콜백함수
    global image # 전역변수
    
    res = value - int(image[0][0])  #트랙바 값 - 이미지 화소
    image = image + res
    cv2.imshow(title01,image)

def onMouse(event,x,y,flags,param): #마우스 콜백함수
    global image # 전역변수
    
    if event ==cv2.EVENT_LBUTTONDOWN:
        if(image[0][0] >= 10):
            image = image - 10
        cv2.setTrackbarPos("MyTrack","test01",image[0][0])
        print("누름")
    
    elif event ==cv2.EVENT_RBUTTONDOWN:
        print("오른쪽 마우스 클릭",event,x,y,flags,param)

image = np.zeros((300,500),np.uint8) #배열로 이미지 생성

title01 = "test01"  #윈도우타이틀 값
cv2.imshow(title01, image)

# 트랙바 연동
cv2.createTrackbar("Mytrack","test01",image[0][0],255,onChange) #마우스 콜백 함수
cv2.setMouseCallback("test01",onMouse) #마우스 콜백 함수
cv2.waitKey(0)  #키 이벤트
cv2.destroyAllWindows() # 객체소멸

누름
누름
누름
누름
누름
누름
누름
누름
누름
누름
누름
누름
누름
누름
누름


In [34]:
#6) 도형그리기와 이벤트
# 왼쪽 버튼을 클릭하게 되면 사각형을 그리자
import numpy as np
import cv2

def onMouse(event,x,y,flags,param): #마우스 콜백함수
    global pt # 전역변수
    if event ==cv2.EVENT_LBUTTONDOWN:
        if pt[0] < 0:
            pt=(x,y)  # 마우스 포인터의 xy값을 지정
        else:
            cv2.rectangle(image,pt,(x,y),(255,0,0),2)
            cv2.imshow(title01, image) # 이미지 보기
            pt = (-1,-1)  #초기값 재설정
    elif event ==cv2.EVENT_RBUTTONDOWN:
        cv2.circle(image,(x,y),50,(0,0,255),2)
        cv2.imshow(title01,image) # 이미지 보기
        pt = (-1,-1)

image = np.full((300,500,3),(255,255,255),np.uint8)

#초기좌표
pt = (-1,-1)
title01 = "test01"  #윈도우타이틀 값
cv2.imshow(title01, image)

cv2.setMouseCallback("test01",onMouse) #마우스 콜백 함수

cv2.waitKey(0)  #키 이벤트
cv2.destroyAllWindows() # 객체소멸

In [36]:
#6) 도형그리기와 이벤트
# 왼쪽 버튼을 클릭하게 되면 사각형을 그리자
import numpy as np
import cv2
import math

def onMouse(event,x,y,flags,param): #마우스 콜백함수
    global pt # 전역변수
    if event ==cv2.EVENT_LBUTTONDOWN:
        pt=(x,y)  # 마우스 포인터의 xy값을 지정
    
    elif event ==cv2.EVENT_LBUTTONUP:
        cv2.rectangle(image,pt,(x,y),(255,0,0),2)
        cv2.imshow(title01, image) # 이미지 보기
        pt = (-1,-1)  #초기값 재설정
        
    elif event ==cv2.EVENT_RBUTTONDOWN:
        pt=(x,y)  # 마우스 포인터의 xy값을 지정
    
    elif event ==cv2.EVENT_RBUTTONUP:
        cv2.circle(image,pt,int(dotdistance(pt,(x,y))),(0,0,255),2)
        cv2.imshow(title01,image) # 이미지 보기
        pt = (-1,-1)
        
def dotdistance(a,b):
    dis = math.sqrt((b[0]-a[0])**2+(b[1]-a[1])**2)
    return dis

image = np.full((300,500,3),(255,255,255),np.uint8)

#초기좌표
pt = (-1,-1)
title01 = "test01"  #윈도우타이틀 값
cv2.imshow(title01, image)

cv2.setMouseCallback("test01",onMouse) #마우스 콜백 함수

cv2.waitKey(0)  #키 이벤트
cv2.destroyAllWindows() # 객체소멸