RNN(Recurrent Neural Network) : 기존의 신경망은 입력된 데이터의 길이가 정해졌으나
다양한 길이의 입력 시퀀스가 생겨나서 구현된 신경망(자연어처리, 스팸처리, (좋아요, 싫어요))
ex)움직이는 객체의 경로를 저장해서 판별하는 것. 사람의 동작을 포함한 것은 RNN이 가진다.
CNN / RNN -> GAN(생성모델) : 모션작곡, 자율주행, 홈트 등등

 - 입력과 출력을 시퀀스 단위로 처리하는 모델 <번역> 입력된문장 (단어) -> 출력된문장(단어)
 - 순환 신경망(RNN)과 재귀 신경망과는 완전 다른 개념의 모델
 - 노드 셀을 만들어서 입력과 출력 사이에서 순혼 할 수 있도록 구현된다.
   Xt -> Cell(메모리 셀, Rnn 셀) -> Yt
 - 메모리셀은 각각의 시점 (t)을 가지고 바로 이전의 입력한 시점에서 전달해온 데이터를 가지고 재귀적인 활동을 한다. t+1 => Cell
 - t 시점에서 메모리 셀은 t-1 시점의 메모리 셀이 보낸 은닉상태의 값을 t 시점의 은닉상태 계산을 위한 입력 값이다.
   ex) "나는 금요일이 좋다"
     Xt ->        Cell(메모리 셀, Rnn 셀) -> Yt
     
 - 일 대 다 : 입력하나 -> 셀 많이 -> 출력 많이 ex)사진하나 -> 여러개의 제목(사진제목이 단어 시퀀스 출력)
 - 다 대 일 : 입력 많이 -> 셀 많이 -> 출력 하나  ex) 감성분류, 스팸분류
 - 다 대 다 : 입력, 셀, 출력 많이 -> 번역처리
 
 - RNN의 은닉층 연산은 행렬연산.
 ex) model.add(simpleRNN(hidden_size), input_shape = ())

In [4]:
#ex) RNN층을 만들어 보자.
from keras.models import *
from keras.layers import SimpleRNN

model = Sequential()
model. add(SimpleRNN(3, input_shape =(2,10), return_sequences = True))  #(None, 3)
#model. add(SimpleRNN(3, batch_input_shape =(8,2,10), return_sequences = True))
model.summary()
           

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_3 (SimpleRNN)     (None, 2, 3)              42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


 - 일련의 순서 신경망 '단어 4개 = 4개의 신경망
 - t 시점에서 메모리 셀은 t-1 시점의 메모리 셀이 보낸 은닉상태의 값을 t 시점의 은닉상태 계산을 위한 입력 값이다.
 - x(1)은 one-hot 연산을 구현한다.
 - s(t) : 넽웍에서 기억하는 공간
   St = f(Uxt + Wst-1) 이때 함수로 비선형 함수가 된다.
 - Ot = t의 출력값 (문장에 출현 예측)
 
 - Ot = softmax(Vst)
 - LSTM(Long Short Term Memory) : 장단기 메모리로 은닉층의 메모리셀에 입력게이트, 소멸게이트, 출력게이트를
   추가해서 불필요한 기억은 지우고 기억해야 되는 내용들을 저장한다. 각각의 게이트에는 시그모이드 함수가 존재한다.
   시그모이드함수를 지나면 0,1 값이 나오게 되는데 이값들을 가지고 게이트가 조절된다.

In [5]:
import numpy as np
import tensorflow as tf
#RNN은 텐서를 받을때 3D 텐서를 받는다
#만일 2D 텐서가 들어온다면 3D로 변경해줘야 한다.

inputs = np.random.random([32,10,8]).astype(np.float32)
simple_rnn = tf.keras.layers.SimpleRNN(4)
#print(inputs)

output = simple_rnn(inputs) # The Output has shape '[32,4]'
print(output)
#return_sequences 히든레이어를 확인 시켜준다,.
simple_rnn = tf.keras.layers.SimpleRNN(4, return_sequences = True, return_state = True)
simple_rnn

#whole_sequence_output has shape '[32,10,4]'
# final_state has shape '[32,4]'
whole_sequence_output, final_state = simple_rnn(inputs)

tf.Tensor(
[[-0.5830291  -0.6245827  -0.9303139   0.08409714]
 [ 0.5839203  -0.70715725 -0.8264405  -0.78320944]
 [-0.50610864 -0.5243976  -0.80418247  0.46438208]
 [ 0.28761122 -0.6394619  -0.79526025 -0.6175144 ]
 [ 0.4410587  -0.6094529  -0.7492597   0.16639543]
 [-0.40987927 -0.78644425 -0.8937732   0.271622  ]
 [-0.15111381 -0.5714589  -0.65993685 -0.6181043 ]
 [ 0.10160635 -0.73445964 -0.8578138  -0.86806923]
 [-0.31592685 -0.6302544  -0.5775584  -0.803648  ]
 [-0.06553799 -0.9549781  -0.7111652  -0.74051917]
 [ 0.60147214 -0.7582651  -0.42589512 -0.5682119 ]
 [-0.72933465 -0.80491954 -0.79919297 -0.6516444 ]
 [ 0.5158129  -0.22055125 -0.76340884 -0.16806725]
 [-0.6609605  -0.8379744  -0.84328884 -0.75087184]
 [ 0.1599396  -0.49723154 -0.7874414  -0.2591087 ]
 [-0.20234174 -0.4912249  -0.9168611   0.28574648]
 [ 0.5491436  -0.30608028 -0.67931956 -0.10864364]
 [ 0.3058426  -0.9089228  -0.709946   -0.71481   ]
 [-0.15423614 -0.0460488  -0.39968354 -0.03631032]
 [-0.21112077 -0.308